---
general:
  BATCH_SIZE: 400
  LOSS_FUNCTION:
    _component_: torch.nn.CrossEntropyLoss
train:
  EPOCH_NUM: 200
  LEARNING_RATE: 1e-4
validate:
  blank: 'blank'
run:
  WEIGHTS_CDR3: './tcrenc/models/autoencoder_onehot/weights/cdr3_model_final_restructed.pth'
  WEIGHTS_EPIOPE: './tcrenc/models/autoencoder_onehot/weights/epitope_model_final_restructed.pth'