---
general:
  LINEAR_PART: 19
  BATCH_SIZE: 64
  LOSS_FUNCTION:
    _component_: torch.nn.MSELoss
train:
  EPOCH_NUM: 100
  LEARNING_RATE: 1e-3
validate:
  blank: 'blank'
run:
  WEIGHTS_CDR3: './tcrenc/models/autoencoder_kidera/weights/cdr3.pth'
  WEIGHTS_EPIOPE: './tcrenc/models/autoencoder_onehot/weights/epitope.pth'